const PRESET_SKILLS = [
  // Frontend Technologies
  "JavaScript",
  "TypeScript",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "HTML",
  "CSS",
  "SCSS",
  "Tailwind CSS",
  "Bootstrap",
  "Material-UI",
  "Chakra UI",
  "jQuery",
  "Redux",
  "MobX",
  "Zustand",
  "Webpack",
  "Vite",
  "Parcel",

  // Backend Technologies
  "Node.js",
  "Express.js",
  "Nest.js",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Java",
  "Spring Boot",
  "Spring Framework",
  "C#",
  ".NET",
  "ASP.NET",
  "PHP",
  "Laravel",
  "Symfony",
  "Ruby",
  "Ruby on Rails",
  "Go",
  "Gin",
  "Rust",
  "Actix",
  "C++",
  "Kotlin",
  "Scala",
  "Clojure",

  // Mobile Development
  "React Native",
  "Flutter",
  "Swift",
  "Objective-C",
  "Kotlin",
  "Java Android",
  "Xamarin",
  "Ionic",
  "Cordova",
  "Unity",
  "Unreal Engine",

  // Databases
  "SQL",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Oracle",
  "SQL Server",
  "MongoDB",
  "Cassandra",
  "DynamoDB",
  "Redis",
  "Elasticsearch",
  "Neo4j",
  "Firebase",
  "Supabase",
  "PlanetScale",
  "Prisma",

  // Cloud & DevOps
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "GitLab CI",
  "GitHub Actions",
  "CircleCI",
  "Terraform",
  "Ansible",
  "Vagrant",
  "Chef",
  "Puppet",
  "Nginx",
  "Apache",
  "Linux",
  "Ubuntu",

  // Data Science & AI/ML
  "R",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "OpenCV",
  "NLTK",
  "SpaCy",
  "Jupyter",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "Apache Spark",
  "Hadoop",
  "Machine Learning",
  "Deep Learning",
  "Computer Vision",
  "NLP",
  "Data Analysis",
  "Data Visualization",
  "Big Data",
  "Data Mining",
  "Statistical Analysis",

  // Testing
  "Jest",
  "Cypress",
  "Selenium",
  "Playwright",
  "Puppeteer",
  "TestNG",
  "JUnit",
  "Mocha",
  "Chai",
  "Enzyme",
  "React Testing Library",
  "Postman",
  "Insomnia",
  "K6",
  "Artillery",

  // Version Control & Collaboration
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "SVN",
  "Mercurial",
  "Jira",
  "Confluence",
  "Slack",
  "Microsoft Teams",
  "Notion",
  "Asana",
  "Trello",
  "Monday.com",

  // Design & UI/UX
  "Figma",
  "Adobe XD",
  "Sketch",
  "Photoshop",
  "Illustrator",
  "InVision",
  "Principle",
  "Framer",
  "Zeplin",
  "Abstract",
  "UI Design",
  "UX Design",
  "User Research",
  "Wireframing",
  "Prototyping",
  "Design Systems",
  "Responsive Design",
  "Accessibility (A11y)",
  "Typography",
  "Color Theory",
  "Interaction Design",
  "Information Architecture",
  "Usability Testing",

  // Digital Marketing
  "SEO",
  "SEM",
  "Google Analytics",
  "Google Ads",
  "Facebook Ads",
  "Instagram Marketing",
  "LinkedIn Marketing",
  "Twitter Marketing",
  "TikTok Marketing",
  "YouTube Marketing",
  "Content Marketing",
  "Email Marketing",
  "Marketing Automation",
  "Mailchimp",
  "HubSpot",
  "Marketo",
  "Salesforce Marketing Cloud",
  "Copywriting",
  "Content Strategy",
  "Social Media Marketing",
  "Social Media Management",
  "Influencer Marketing",
  "Affiliate Marketing",
  "Growth Hacking",
  "Conversion Rate Optimization",
  "A/B Testing",
  "Landing Page Optimization",
  "Marketing Analytics",
  "Customer Acquisition",
  "Retention Marketing",
  "Brand Management",
  "Brand Strategy",
  "Product Marketing",
  "Performance Marketing",
  "Display Advertising",
  "Programmatic Advertising",
  "Native Advertising",
  "Video Marketing",
  "Podcast Marketing",
  "Mobile Marketing",
  "App Store Optimization",
  "Webinar Marketing",
  "Event Marketing",
  "PR & Communications",
  "Media Planning",
  "Campaign Management",

  // SEO Specific
  "On-Page SEO",
  "Off-Page SEO",
  "Technical SEO",
  "Local SEO",
  "International SEO",
  "Link Building",
  "Keyword Research",
  "SEMrush",
  "Ahrefs",
  "Moz",
  "Google Search Console",
  "Schema Markup",
  "Sitemap Optimization",
  "Robots.txt",
  "Core Web Vitals",

  // E-commerce & Sales
  "Shopify",
  "WooCommerce",
  "Magento",
  "BigCommerce",
  "Amazon FBA",
  "Dropshipping",
  "E-commerce Management",
  "Payment Gateway Integration",
  "Inventory Management",
  "Order Fulfillment",
  "Customer Service",
  "Sales Strategy",
  "B2B Sales",
  "B2C Sales",
  "Inside Sales",
  "Field Sales",
  "Account Management",
  "Business Development",
  "Lead Generation",
  "Sales Forecasting",
  "CRM",
  "Salesforce",
  "HubSpot CRM",
  "Zoho CRM",
  "Pipedrive",
  "Cold Calling",
  "Negotiation",
  "Closing Deals",

  // Human Resources
  "Recruitment",
  "Talent Acquisition",
  "Interviewing",
  "Candidate Sourcing",
  "LinkedIn Recruiting",
  "Boolean Search",
  "Applicant Tracking Systems",
  "Greenhouse",
  "Lever",
  "Workday",
  "BambooHR",
  "Employee Onboarding",
  "Employee Relations",
  "Performance Management",
  "Compensation & Benefits",
  "Payroll Management",
  "HR Compliance",
  "Labor Law",
  "Employment Law",
  "HRIS",
  "Talent Management",
  "Learning & Development",
  "Training & Development",
  "Organizational Development",
  "Change Management",
  "Employee Engagement",
  "Culture Building",
  "Diversity & Inclusion",
  "HR Analytics",
  "Workforce Planning",
  "Succession Planning",
  "Conflict Resolution",
  "Employee Retention",
  "Exit Interviews",

  // Finance & Accounting
  "Financial Analysis",
  "Financial Modeling",
  "Budgeting",
  "Forecasting",
  "Accounting",
  "Bookkeeping",
  "QuickBooks",
  "Xero",
  "SAP",
  "Oracle Financials",
  "Financial Reporting",
  "GAAP",
  "IFRS",
  "Tax Preparation",
  "Audit",
  "Cost Accounting",
  "Management Accounting",
  "Accounts Payable",
  "Accounts Receivable",
  "Cash Flow Management",
  "Investment Analysis",
  "Portfolio Management",
  "Risk Management",
  "Financial Planning",
  "Wealth Management",
  "Corporate Finance",
  "Mergers & Acquisitions",
  "Due Diligence",
  "Valuation",
  "Excel",
  "VBA",
  "Power BI",
  "Tableau",

  // Project Management & Methodologies
  "Agile",
  "Scrum",
  "Kanban",
  "Waterfall",
  "Lean",
  "Six Sigma",
  "PMP",
  "PRINCE2",
  "DevOps",
  "CI/CD",
  "TDD",
  "BDD",
  "DDD",
  "Microservices",
  "REST API",
  "GraphQL",
  "gRPC",
  "WebSockets",
  "OAuth",
  "JWT",
  "Risk Management",
  "Stakeholder Management",
  "Resource Planning",
  "Gantt Charts",
  "MS Project",
  "Smartsheet",

  // Business Analysis & Strategy
  "Business Analysis",
  "Requirements Gathering",
  "Process Mapping",
  "Process Improvement",
  "Business Process Management",
  "Gap Analysis",
  "SWOT Analysis",
  "Competitive Analysis",
  "Market Research",
  "Strategic Planning",
  "Business Strategy",
  "Business Intelligence",
  "Data-Driven Decision Making",
  "KPI Development",
  "Metrics & Reporting",
  "Consulting",
  "Change Management",
  "Vendor Management",
  "Contract Negotiation",

  // Legal & Compliance
  "Contract Law",
  "Intellectual Property",
  "GDPR",
  "Data Privacy",
  "Compliance Management",
  "Regulatory Compliance",
  "Corporate Law",
  "Legal Research",
  "Legal Writing",
  "Litigation",
  "Arbitration",
  "Mediation",

  // Customer Success & Support
  "Customer Success",
  "Customer Support",
  "Technical Support",
  "Help Desk",
  "Zendesk",
  "Freshdesk",
  "Intercom",
  "Customer Experience",
  "Customer Journey Mapping",
  "Churn Reduction",
  "Net Promoter Score",
  "Customer Satisfaction",
  "Account Management",
  "Client Relations",
  "Troubleshooting",

  // Operations & Supply Chain
  "Operations Management",
  "Supply Chain Management",
  "Logistics",
  "Procurement",
  "Vendor Management",
  "Inventory Management",
  "Warehouse Management",
  "Quality Assurance",
  "Quality Control",
  "Lean Manufacturing",
  "Process Optimization",
  "ERP Systems",
  "SAP",
  "Oracle",

  // Specialized Technical Skills
  "Blockchain",
  "Ethereum",
  "Solidity",
  "Web3",
  "Smart Contracts",
  "Cryptocurrency",
  "NFT",
  "DeFi",
  "Cybersecurity",
  "Information Security",
  "Network Security",
  "Penetration Testing",
  "Ethical Hacking",
  "CISSP",
  "CEH",
  "Security Auditing",
  "Incident Response",
  "Malware Analysis",
  "Cryptography",
  "Game Development",
  "AR/VR",
  "Augmented Reality",
  "Virtual Reality",
  "IoT",
  "Embedded Systems",
  "Firmware",
  "Hardware Development",
  "Circuit Design",
  "PCB Design",
  "Robotics",
  "Automation",
  "RPA",
  "UiPath",
  "Automation Anywhere",
  "Blue Prism",

  // Content Creation & Media
  "Content Writing",
  "Technical Writing",
  "Creative Writing",
  "Blogging",
  "Journalism",
  "Editing",
  "Proofreading",
  "Translation",
  "Video Editing",
  "Adobe Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "After Effects",
  "Motion Graphics",
  "Animation",
  "3D Modeling",
  "Blender",
  "Maya",
  "3ds Max",
  "Cinema 4D",
  "Photography",
  "Videography",
  "Audio Production",
  "Sound Design",
  "Music Production",
  "Ableton",
  "Logic Pro",
  "Pro Tools",
  "Podcast Production",
  "Voice Over",
  "Scriptwriting",
  "Storyboarding",

  // Soft Skills & Leadership
  "Leadership",
  "Team Management",
  "People Management",
  "Communication",
  "Verbal Communication",
  "Written Communication",
  "Presentation Skills",
  "Public Speaking",
  "Problem Solving",
  "Critical Thinking",
  "Analytical Thinking",
  "Creative Thinking",
  "Decision Making",
  "Time Management",
  "Organizational Skills",
  "Multitasking",
  "Attention to Detail",
  "Adaptability",
  "Flexibility",
  "Collaboration",
  "Teamwork",
  "Cross-functional Collaboration",
  "Emotional Intelligence",
  "Empathy",
  "Active Listening",
  "Conflict Management",
  "Mentoring",
  "Coaching",
  "Training",
  "Facilitation",
  "Influence",
  "Persuasion",
  "Networking",
  "Relationship Building",
  "Customer Focus",
  "Results-Oriented",
  "Goal Setting",
  "Self-Motivation",
  "Initiative",
  "Accountability",
  "Work Ethic",
  "Professionalism",
  "Stress Management",
  "Resilience",

  // Languages
  "English",
  "Spanish",
  "Mandarin Chinese",
  "French",
  "German",
  "Japanese",
  "Korean",
  "Italian",
  "Portuguese",
  "Russian",
  "Arabic",
  "Hindi",
  "Bengali",

  // Industry-Specific
  "Healthcare",
  "Telemedicine",
  "Medical Coding",
  "HIPAA Compliance",
  "Electronic Health Records",
  "Clinical Research",
  "Pharmaceutical",
  "Biotechnology",
  "Manufacturing",
  "Real Estate",
  "Property Management",
  "Construction Management",
  "Architecture",
  "AutoCAD",
  "Revit",
  "SketchUp",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Environmental Science",
  "Sustainability",
  "Renewable Energy",
  "Education",
  "Curriculum Development",
  "Instructional Design",
  "E-Learning",
  "LMS",
  "Hospitality",
  "Hotel Management",
  "Event Planning",
  "Catering",
  "Tourism",
  "Transportation",
  "Aviation",
  "Maritime",
  "Agriculture",
  "Food Science",
];

export default PRESET_SKILLS;
